# Site
title:              Tell me what you buy and I will tell you who you are
bio:                'Project bio'
description:        "Project description"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
github:             marvande/epfl-ada-2019-project-bubble582

# personal
location:           EPFL, Lausanne
email:              marijn.vandermeer@epfl.ch # change this to your email to receive free emails for your contact submissions via Slapform.com

# Team names, titles and social links
people:
- name: Lou Locci
  pic: 2
  social:
    - title: github
      url: https://github.com/Loulocci
    - title: linkedin
      url: https://www.linkedin.com/in/lou-locci-525350131/

- name: Amandine Goffeney
  pic: 1
  social:
    - title: github
      url: https://github.com/amandinegoffeney
    - title: linkedin
      url: https://www.linkedin.com/in/amandine-goffeney/

- name: Marijn van der Meer
  pic: 3
  social:
    - title: github
      url: https://github.com/marvande
    - title: linkedin
      url: https://www.linkedin.com/in/marijn-van-der-meer/

- name: Marco Pietro Abrate
  pic: 4
  social:
    - title: github
      url: https://github.com/marcoabrate
    - title: linkedin
      url: https://www.linkedin.com/in/marcoabrate/


# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
